### ISSUE TITLE
Capabilities checklist

### ISSUE THREAD

**Issue by txvvgnx** [txvvgnx/EZTelemetry#1]
Check if Flutter is able to do the following:
Google Maps:
- [ ] Can we add widgets as custom markers?
- [ ] Can we draw polylines between points, including from the user to the rocket marker?
- [ ] Can we change the zoom settings on the fly? (or more practically, set the map bounds?)
- [ ] How does the caching behaviour work when the current tab is not focused?

Graphs:
- [ ] Can the graph accommodate dynamically growing time-series data?
- [ ] How does the caching behaviour work when the current tab is not focused?

3D viewer:

- [ ] Are object rotations possible? (yes)
- [ ] Can the viewer be overlayed over other widgets?

Sensors and measurement:
- [ ] Can we produce accurate compass readings?
- [ ] Can we produce accurate pitch/elevation angle readings?

**Comment by txvvgnx** [comment]
- [ ] Map distance graph as a substitute if Google Maps is inaccessible due to launch site connectivity problems
